name: Selenium Tests

on:
  push:
    branches:
      - Actions

jobs:
  selenium-tests:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1'  # Puedes ajustar la versión según tus necesidades

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and test
      run: dotnet test
